---
abstract: 'solve a CAPTCHA before some actions in RT'
author:
  - 'Ruslan Zakirov <ruz@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-Captcha
no_index:
  directory:
    - etc
    - html
    - inc
requires:
  GD::SecurityImage: 0
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
